// assets.h
// Generated by OpenGL Asset Forge
// 2026-01-08T21:04:15.308Z
// Modern OpenGL 3.3+ Compatible

#ifndef ASSETS_H
#define ASSETS_H

#include <glad/glad.h>
#include <unordered_map>
#include <string>

namespace Assets {

    // --- Shape: triangle_0 (GL_TRIANGLES, 3 vertices) ---
    const float triangle_0_vertices[] = {
        // x,       y,       r,       g,       b,       a
        -0.1501f, 0.6952f, 0.0706f, 0.7294f, 0.5098f, 1.0f,
        -0.7991f, -0.1409f, 0.0706f, 0.7294f, 0.5098f, 1.0f,
        0.3372f, -0.5242f, 0.0706f, 0.7294f, 0.5098f, 1.0f
    };
    const int triangle_0_count = 3;
    const GLenum triangle_0_primitive = GL_TRIANGLES;

    // --- Shape: circle_1767905488852 (GL_TRIANGLE_FAN, 66 vertices) ---
    const float circle_1767905488852_vertices[] = {
        // x,       y,       r,       g,       b,       a
        0.4734f, 0.6905f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.7378f, 0.6905f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.7365f, 0.7164f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.7327f, 0.7421f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.7264f, 0.7673f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.7177f, 0.7917f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.7066f, 0.8152f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.6933f, 0.8374f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.6778f, 0.8583f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.6604f, 0.8775f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.6412f, 0.8949f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.6203f, 0.9104f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.5981f, 0.9237f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.5746f, 0.9348f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.5502f, 0.9435f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.5250f, 0.9498f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.4994f, 0.9536f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.4734f, 0.9549f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.4475f, 0.9536f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.4219f, 0.9498f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.3967f, 0.9435f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.3723f, 0.9348f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.3488f, 0.9237f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.3266f, 0.9104f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.3057f, 0.8949f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.2865f, 0.8775f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.2691f, 0.8583f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.2536f, 0.8374f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.2403f, 0.8152f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.2292f, 0.7917f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.2204f, 0.7673f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.2141f, 0.7421f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.2103f, 0.7164f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.2091f, 0.6905f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.2103f, 0.6646f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.2141f, 0.6390f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.2204f, 0.6138f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.2292f, 0.5894f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.2403f, 0.5659f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.2536f, 0.5436f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.2691f, 0.5228f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.2865f, 0.5036f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.3057f, 0.4862f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.3266f, 0.4707f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.3488f, 0.4574f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.3723f, 0.4463f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.3967f, 0.4375f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.4219f, 0.4312f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.4475f, 0.4274f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.4734f, 0.4261f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.4994f, 0.4274f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.5250f, 0.4312f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.5502f, 0.4375f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.5746f, 0.4463f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.5981f, 0.4574f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.6203f, 0.4707f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.6412f, 0.4862f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.6604f, 0.5036f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.6778f, 0.5228f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.6933f, 0.5436f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.7066f, 0.5659f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.7177f, 0.5894f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.7264f, 0.6138f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.7327f, 0.6390f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.7365f, 0.6646f, 1.0000f, 0.1216f, 0.9255f, 1.0f,
        0.7378f, 0.6905f, 1.0000f, 0.1216f, 0.9255f, 1.0f
    };
    const int circle_1767905488852_count = 66;
    const GLenum circle_1767905488852_primitive = GL_TRIANGLE_FAN;

    // --- Shape: rect_1767905494562 (GL_TRIANGLES, 6 vertices) ---
    const float rect_1767905494562_vertices[] = {
        // x,       y,       r,       g,       b,       a
        0.6744f, -0.6813f, 0.0706f, 0.7294f, 0.5098f, 1.0f,
        0.9630f, -0.6813f, 0.0706f, 0.7294f, 0.5098f, 1.0f,
        0.9630f, 0.0277f, 0.0706f, 0.7294f, 0.5098f, 1.0f,
        0.6744f, -0.6813f, 0.0706f, 0.7294f, 0.5098f, 1.0f,
        0.9630f, 0.0277f, 0.0706f, 0.7294f, 0.5098f, 1.0f,
        0.6744f, 0.0277f, 0.0706f, 0.7294f, 0.5098f, 1.0f
    };
    const int rect_1767905494562_count = 6;
    const GLenum rect_1767905494562_primitive = GL_TRIANGLES;

    // --- Shape: triangle_3 (GL_TRIANGLES, 3 vertices) ---
    const float triangle_3_vertices[] = {
        // x,       y,       r,       g,       b,       a
        -0.8048f, 0.9098f, 0.0706f, 0.7294f, 0.5098f, 1.0f,
        -0.8655f, 0.4176f, 0.0706f, 0.7294f, 0.5098f, 1.0f,
        -0.2356f, 0.8211f, 0.0706f, 0.7294f, 0.5098f, 1.0f
    };
    const int triangle_3_count = 3;
    const GLenum triangle_3_primitive = GL_TRIANGLES;

    // --- Shape: rect_1767906246962 (GL_TRIANGLES, 6 vertices) ---
    const float rect_1767906246962_vertices[] = {
        // x,       y,       r,       g,       b,       a
        -0.8748f, -0.9215f, 0.0706f, 0.7294f, 0.5098f, 1.0f,
        0.1703f, -0.9215f, 0.0706f, 0.7294f, 0.5098f, 1.0f,
        0.1703f, -0.6695f, 0.0706f, 0.7294f, 0.5098f, 1.0f,
        -0.8748f, -0.9215f, 0.0706f, 0.7294f, 0.5098f, 1.0f,
        0.1703f, -0.6695f, 0.0706f, 0.7294f, 0.5098f, 1.0f,
        -0.8748f, -0.6695f, 0.0706f, 0.7294f, 0.5098f, 1.0f
    };
    const int rect_1767906246962_count = 6;
    const GLenum rect_1767906246962_primitive = GL_TRIANGLES;

    // --- Shape data structure for runtime management ---
    struct ShapeData {
        const float* vertices;
        int count;
        GLenum primitive;
        unsigned int VAO = 0;
        unsigned int VBO = 0;
    };

    // --- Shape registry (lazy-initialized singleton) ---
    inline std::unordered_map<std::string, ShapeData>& getShapes() {
        static std::unordered_map<std::string, ShapeData> shapes = {
            {"triangle_0", {triangle_0_vertices, triangle_0_count, triangle_0_primitive}},
            {"circle_1767905488852", {circle_1767905488852_vertices, circle_1767905488852_count, circle_1767905488852_primitive}},
            {"rect_1767905494562", {rect_1767905494562_vertices, rect_1767905494562_count, rect_1767905494562_primitive}},
            {"triangle_3", {triangle_3_vertices, triangle_3_count, triangle_3_primitive}},
            {"rect_1767906246962", {rect_1767906246962_vertices, rect_1767906246962_count, rect_1767906246962_primitive}}
        };
        return shapes;
    }

    // --- Initialize VAO/VBO for a single shape ---
    inline void initShape(const std::string& name) {
        auto& shapes = getShapes();
        auto it = shapes.find(name);
        if (it == shapes.end()) return;
        ShapeData& s = it->second;
        if (s.VAO != 0) return; // Already initialized

        glGenVertexArrays(1, &s.VAO);
        glGenBuffers(1, &s.VBO);
        glBindVertexArray(s.VAO);
        glBindBuffer(GL_ARRAY_BUFFER, s.VBO);
        glBufferData(GL_ARRAY_BUFFER, s.count * 6 * sizeof(float), s.vertices, GL_STATIC_DRAW);

        // Position attribute (location = 0)
        glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 6 * sizeof(float), (void*)0);
        glEnableVertexAttribArray(0);

        // Color attribute (location = 1)
        glVertexAttribPointer(1, 4, GL_FLOAT, GL_FALSE, 6 * sizeof(float), (void*)(2 * sizeof(float)));
        glEnableVertexAttribArray(1);

        glBindVertexArray(0);
    }

    // --- Initialize all shapes ---
    inline void initAllShapes() {
        for (auto& pair : getShapes()) {
            initShape(pair.first);
        }
    }

    // --- Draw a single shape by name ---
    inline void drawShape(const std::string& name) {
        auto& shapes = getShapes();
        auto it = shapes.find(name);
        if (it == shapes.end()) return;
        ShapeData& s = it->second;
        if (s.VAO == 0) initShape(name);
        glBindVertexArray(s.VAO);
        glDrawArrays(s.primitive, 0, s.count);
    }

    // --- Draw all shapes ---
    inline void drawAll() {
        for (auto& pair : getShapes()) {
            drawShape(pair.first);
        }
    }

    // --- Cleanup all GPU resources ---
    inline void cleanup() {
        for (auto& pair : getShapes()) {
            ShapeData& s = pair.second;
            if (s.VAO) {
                glDeleteVertexArrays(1, &s.VAO);
                s.VAO = 0;
            }
            if (s.VBO) {
                glDeleteBuffers(1, &s.VBO);
                s.VBO = 0;
            }
        }
    }

} // namespace Assets

#endif // ASSETS_H
